version: "3.8"

services:
  db:
    image: "postgres:14-alpine"
    container_name: "django-rest-template_db"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    restart: always

  django-rest-template:
    image: "django-rest-template"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "django-rest-template"
    volumes:
      - .:/opt/django-rest-template
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
    postgresql-data:
